version: '3.4'
services:
    app:
        build:
            context: .
            dockerfile: ./build/Dockerfile.app
        depends_on: 
            - db
        env_file: 
            - ./server/.env
        ports:
            - "8888:3000"
        volumes:
            - ./server:/app
            - /app/node_modules  
    db:
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=techhunt2020
        volumes:
            - "dbdata:/var/lib/postgresql/data"
volumes:
    dbdata:
        
        
