CREATE DATABASE IF NOT EXISTS techhunt2020 ;

CREATE TABLE IF NOT EXISTS users(
    id VARCHAR(100) PRIMARY KEY,
    login VARCHAR(100), 
    name VARCHAR(100),
    salary NUMERIC(10, 2),
    CONSTRAINT users_login UNIQUE(login) DEFERRABLE INITIALLY DEFERRED
);
